// JS
//import './js/'
import 'popper.js'
import 'webpack-jquery-ui'
import 'webpack-jquery-ui/css'
import './modules/dropdown/dropdown'
import './modules/range-slider/range-slider'
import './modules/text-field/maskedinput'
import './modules/datepicker/datepicker'
import 'slick-carousel/slick/slick'
import './modules/card-hotel/card-hotel-sllider'
// SCSS
import './pages/main.scss'
